[package]
name = "oxphys_numerics"
version = "0.1.0"
edition = "2021"

[dependencies]
cranelift-codegen = "0.114"
cranelift-module = "0.114"
cranelift-jit = "0.114"
cranelift-frontend = "0.114"
cranelift-native = "0.114"
